//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation
    {
        public int NumeroAffectation { get; set; }
        public System.DateTime DateAffectation { get; set; }
        public int idInfirmier { get; set; }
        public Nullable<int> NumeroStation { get; set; }
    
        public virtual Infirmier Infirmier { get; set; }
        public virtual Station Station { get; set; }
    }
}
