//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation
    {
        public int NumeroAffectation { get; set; }
        public System.DateTime DateAffectation { get; set; }
        public int idInfirmier { get; set; }
        public Nullable<int> NumeroStation { get; set; }
    
        public virtual Infirmier Infirmier { get; set; }
        public virtual Station Station { get; set; }
    }
}
