//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierVaccin
    {
        public int NumeroDossierV { get; set; }
        public System.DateTime DateCreationD { get; set; }
        public Nullable<int> NombreDoses { get; set; }
        public Nullable<System.DateTime> DatePremiereDose { get; set; }
        public Nullable<System.DateTime> DateDeuxiemeDose { get; set; }
        public int idPrepose { get; set; }
        public int NSS { get; set; }
        public int NumeroStation { get; set; }
        public Nullable<int> Alergie { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Prepose Prepose { get; set; }
        public virtual Station Station { get; set; }
    }
}
