//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierVaccin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DossierVaccin()
        {
            this.Vaccins = new HashSet<Vaccin>();
        }
    
        public int NumeroDossierV { get; set; }
        public System.DateTime DateCreationD { get; set; }
        public Nullable<int> NombreDoses { get; set; }
        public Nullable<System.DateTime> DatePremiereDose { get; set; }
        public Nullable<System.DateTime> DateDeuxiemeDose { get; set; }
        public int idPrepose { get; set; }
        public int NSS { get; set; }
        public int NumeroStation { get; set; }
        public Nullable<int> Alergie { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Prepose Prepose { get; set; }
        public virtual Station Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccin> Vaccins { get; set; }
    }
}
