//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccin
    {
        public int NumeroVaccin { get; set; }
        public string Marque { get; set; }
        public Nullable<int> NumeroStation { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
