//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccin
    {
        public int NumeroVaccin { get; set; }
        public string Marque { get; set; }
        public Nullable<int> NumeroDossierV { get; set; }
    
        public virtual DossierVaccin DossierVaccin { get; set; }
    }
}
