//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHopital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccin
    {
        public int NumeroVaccin { get; set; }
        public string Marque { get; set; }
        public Nullable<int> NumeroDossierV { get; set; }
    
        public virtual DossierVaccin DossierVaccin { get; set; }
    }
}
